// =============================================================================
// BANCO DE ALIMENTOS - PRODUCT CONFIGURATION
// =============================================================================

// Centralized server configuration - SINGLE SOURCE OF TRUTH
const BANCO_CONFIG = {
    BASE_URL: "https://bancodealimentos.or.cr",
    get SERVER_URL() { return this.BASE_URL; },
    get SHOP_URL() { return `${this.BASE_URL}/en_US/shop`; },
    QTY: 6, // Default quantity for all products
};

// Configuration array containing all products to monitor and add to cart
// Active products sorted A-Z by name
const BANCO_PRODUCTS = [
    { id: 480, qty: BANCO_CONFIG.QTY, name: 'Aceite de Oliva 15 Lts caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda086-aceite-de-oliva-15-lts-caja-plastica-480?min_price=20.0` },
    { id: 2505, qty: BANCO_CONFIG.QTY, name: 'Aceite y manteca de cocina 10 Lts caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda189-aceite-y-manteca-de-cocina-10-lts-caja-plastica-3791?page=2&min_price=20.0` },
    { id: 460, qty: BANCO_CONFIG.QTY, name: 'Aderezos y Salsas varias 10 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda066-aderezos-y-salsas-varias-10-kg-caja-plastica-460?min_price=20.0` },
    { id: 1958, qty: 0, name: 'Alimento Animal Gato 250 kgs tarima', referrer: `${BANCO_CONFIG.SHOP_URL}/bda351-alimento-animal-gato-250-kgs-tarima-3234?min_price=20.0` },
    { id: 395, qty: 15, name: 'Arroz Varios 20 kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda001-arroz-varios-20-kg-caja-plastica-395?min_price=20.0` },
    { id: 2500, qty: BANCO_CONFIG.QTY, name: 'Azúcar Blanca 15 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda184-azucar-blanca-15-kg-caja-plastica-3786?min_price=20.0` },
    { id: 2507, qty: 1, name: 'Atún con vegetales 10 kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda191-atun-con-vegetales-10-kg-caja-plastica-3793?page=2&min_price=20.0` },
    { id: 410, qty: BANCO_CONFIG.QTY, name: 'Azúcar morena 20 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda016-azucar-morena-20-kg-caja-plastica-410?min_price=20.0` },
    { id: 444, qty: BANCO_CONFIG.QTY, name: 'Avena surtida 8 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda050-avena-surtida-8-kg-caja-plastica-444?min_price=20.0` },
    { id: 1036, qty: BANCO_CONFIG.QTY, name: 'Bebida de Proteína saborizada 12 uds por caja', referrer: `${BANCO_CONFIG.SHOP_URL}/bda112-bebida-de-proteina-saborizada-12-uds-por-caja-2312?min_price=20.0` },
    { id: 525, qty: BANCO_CONFIG.QTY, name: 'Bolsas para alimentos Ziploc 4 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda229-bolsas-para-alimentos-ziploc-4-kg-caja-plastica-525?min_price=20.0` },
    { id: 2504, qty: BANCO_CONFIG.QTY, name: 'Café en polvo 5 kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda188-cafe-en-polvo-5-kg-caja-plastica-3790?page=2&min_price=20.0` },
    { id: 457, qty: BANCO_CONFIG.QTY, name: 'Café para máquina 1 Kg paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda063-cafe-para-maquina-1-kg-paquete-457?page=2&min_price=20.0` },
    { id: 459, qty: BANCO_CONFIG.QTY, name: 'Café instantáneo 1 Kg paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/en_US/shop/bda065-cafe-instantaneo-1-kg-paquete-459?min_price=20.0` },
    { id: 529, qty: BANCO_CONFIG.QTY, name: 'Carbón 250 Kg tarima', referrer: `${BANCO_CONFIG.SHOP_URL}/bda233-carbon-250-kg-tarima-529?min_price=20.0` },
    { id: 401, qty: BANCO_CONFIG.QTY, name: 'Cereal surtido 4 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda007-cereal-surtido-4-kg-caja-plastica-401?min_price=20.0` },
    { id: 4951, qty: 2, name: 'BDA510 Chicles 7 kg por caja', referrer: `${BANCO_CONFIG.SHOP_URL}/en_US/shop/bda510-bda510-chicles-7-kg-por-caja-6239?min_price=20.0` },
    { id: 420, qty: BANCO_CONFIG.QTY, name: 'Chocolate en polvo 1 Kg  paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda026-chocolate-en-polvo-1-kg-paquete-420?page=2&min_price=20.0` },
    { id: 423, qty: 0, name: 'Chocolate varios 10 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda029-chocolate-varios-10-kg-caja-plastica-423?min_price=20.0` },
    { id: 511, qty: BANCO_CONFIG.QTY, name: 'Cloro 15 Lts caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda215-cloro-15-lts-caja-plastica-511?min_price=20.0` },
    { id: 428, qty: BANCO_CONFIG.QTY, name: 'Crema para café 1 kg  paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/en_US/shop/bda034-crema-para-cafe-1-kg-paquete-428?min_price=20.0` },
    { id: 421, qty: BANCO_CONFIG.QTY, name: 'Condimentos varios 1 kg paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda027-condimentos-varios-1-kg-paquete-421?page=2&min_price=20.0` },
    { id: 425, qty: 2, name: 'Confite surtido 10 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda031-confite-surtido-10-kg-caja-plastica-425?min_price=20.0` },
    { id: 4937, qty: 1, name: 'Consomé de pollo caja 5kg', referrer: `${BANCO_CONFIG.SHOP_URL}/bda509-consome-de-pollo-caja-5kg-6225?min_price=20.0` },
    { id: 2637, qty: BANCO_CONFIG.QTY, name: 'Crema para peinar por caja 10 kg', referrer: `${BANCO_CONFIG.SHOP_URL}/bda408-crema-para-peinar-por-caja-10-kg-3923?min_price=20.0` },
    { id: 534, qty: 4, name: 'Detergente líquido 15 Lts caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/en_US/shop/bda238-detergente-liquido-15-lts-caja-plastica-534?min_price=20.0` },
    { id: 566, qty: BANCO_CONFIG.QTY, name: 'Esponja corporal de baño caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda270-esponja-corporal-de-bano-caja-plastica-566?min_price=20.0` },
    { id: 1080, qty: 3, name: 'Enjuague bucal 15 Kg por caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/en_US/shop/bda311-enjuague-bucal-15-kg-por-caja-plastica-2356?min_price=20.0` },
    { id: 571, qty: BANCO_CONFIG.QTY, name: 'Fijador para cabello 10 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda275-fijador-para-cabello-10-kg-caja-plastica-571?min_price=20.0` },
    { id: 2501, qty: 10, name: 'Frijol entero 10 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda185-frijol-entero-10-kg-caja-plastica-3787?page=2&min_price=20.0` },
    { id: 2502, qty: BANCO_CONFIG.QTY, name: 'Galletas Surtidas 5 Kg por caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda186-galletas-surtidas-5-kg-por-caja-plastica-3788?min_price=20.0` },
    { id: 2627, qty: BANCO_CONFIG.QTY, name: 'Galleta molida POZUELO 8 Kg por caja', referrer: `${BANCO_CONFIG.SHOP_URL}/bda500-galleta-molida-pozuelo-8-kg-por-caja-3913?page=2&min_price=20.0` },
    { id: 446, qty: BANCO_CONFIG.QTY, name: 'Garbanzos 15 kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda052-garbanzos-15-kg-caja-plastica-446?min_price=20.0` },
    { id: 450, qty: BANCO_CONFIG.QTY, name: 'Gaseosas varias 12 Lts caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda056-gaseosas-varias-12-lts-caja-plastica-450?min_price=20.0` },
    { id: 458, qty: BANCO_CONFIG.QTY, name: 'Granola 1 kg por paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda064-granola-1-kg-por-paquete-458?min_price=20.0` },
    { id: 409, qty: BANCO_CONFIG.QTY, name: 'Harina 15 kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda015-harina-15-kg-caja-plastica-409?min_price=20.0` },
    { id: 499, qty: BANCO_CONFIG.QTY, name: 'Jabón en Polvo 50 Kg saco', referrer: `${BANCO_CONFIG.SHOP_URL}/bda203-jabon-en-polvo-50-kg-saco-499?min_price=20.0` },
    { id: 506, qty: BANCO_CONFIG.QTY, name: 'Jabón Lavaplatos 15 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda210-jabon-lavaplatos-15-kg-caja-plastica-506?min_price=20.0` },
    { id: 523, qty: BANCO_CONFIG.QTY, name: 'Jabón de tocador 10 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda227-jabon-de-tocador-10-kg-caja-plastica-523?min_price=20.0` },
    { id: 402, qty: BANCO_CONFIG.QTY, name: 'Jugos Surtidos 15 Litros caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda008-jugos-surtidos-15-litros-caja-plastica-402?min_price=20.0` },
    { id: 440, qty: BANCO_CONFIG.QTY, name: 'Leche líquida varios 10 Lts caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda046-leche-liquida-varios-10-lts-caja-plastica-440?page=2&min_price=20.0` },
    { id: 435, qty: BANCO_CONFIG.QTY, name: 'Leche en polvo surtida 10 kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda041-leche-en-polvo-surtida-10-kg-caja-plastica-435?min_price=20.0` },
    { id: 2623, qty: BANCO_CONFIG.QTY, name: 'Limpiador Desinfectante 12 Kg por caja', referrer: `${BANCO_CONFIG.SHOP_URL}/bda405-limpiador-desinfectante-12-kg-por-caja-3909?min_price=20.0` },
    { id: 1014, qty: BANCO_CONFIG.QTY, name: 'Líquidos para limpieza varios 15 K por caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda304-liquidos-para-limpieza-varios-15-k-por-caja-plastica-2290?min_price=20.0` },
    { id: 456, qty: BANCO_CONFIG.QTY, name: 'Maíz dulce 15 kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda062-maiz-dulce-15-kg-caja-plastica-456?min_price=20.0` },
    { id: 2632, qty: BANCO_CONFIG.QTY, name: 'Maní varios 2 kg por caja', referrer: `${BANCO_CONFIG.SHOP_URL}/bda502-mani-varios-2-kg-por-caja-3918?page=2&min_price=20.0` },
    { id: 453, qty: BANCO_CONFIG.QTY, name: 'Mantequilla / Margarina 15 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda059-mantequilla-margarina-15-kg-caja-plastica-453?min_price=20.0` },
    { id: 412, qty: BANCO_CONFIG.QTY, name: 'Masa Varios 15 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda018-masa-varios-15-kg-caja-plastica-412?min_price=20.0` },
    { id: 583, qty: BANCO_CONFIG.QTY, name: 'Mechas / Trapeadores caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda287-mechas-trapeadores-caja-plastica-583?min_price=20.0` },
    { id: 1046, qty: BANCO_CONFIG.QTY, name: 'Mezclas varias 8 Kg por caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda113-mezclas-varias-8-kg-por-caja-plastica-2322?min_price=20.0` },
    { id: 517, qty: 0, name: 'Pañal niño talla XXG 200 Uds paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda221-panal-nino-talla-xxg-200-uds-paquete-517?min_price=20.0` },
    { id: 513, qty: 0, name: 'Pañal Niño talla XG 200 Uds paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda217-panal-nino-talla-xg-200-uds-paquete-513?min_price=20.0` },
    { id: 509, qty: 0, name: 'Pañal niño talla G 200 Uds paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda213-panal-nino-talla-g-200-uds-paquete-509?min_price=20.0` },
    { id: 540, qty: BANCO_CONFIG.QTY, name: 'Papel de cocina varios 5 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda244-papel-de-cocina-varios-5-kg-caja-plastica-540?min_price=20.0` },
    { id: 445, qty: BANCO_CONFIG.QTY, name: 'Pasas 1 Kg paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda051-pasas-1-kg-paquete-445?page=2&min_price=20.0` },
    { id: 411, qty: BANCO_CONFIG.QTY, name: 'Pasta de tomate 10 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda017-pasta-de-tomate-10-kg-caja-plastica-411?min_price=20.0` },
    { id: 413, qty: BANCO_CONFIG.QTY, name: 'Pastas Varias 10 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda019-pastas-varias-10-kg-caja-plastica-413?min_price=20.0` },
    { id: 545, qty: BANCO_CONFIG.QTY, name: 'Platos / vasos / cucharas desechables caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda249-platos-vasos-cucharas-desechables-caja-plastica-545?min_price=20.0` },
    { id: 470, qty: BANCO_CONFIG.QTY, name: 'Polvo para hornear 1 Kg paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda076-polvo-para-hornear-1-kg-paquete-470?min_price=20.0` },
    { id: 560, qty: BANCO_CONFIG.QTY, name: 'Prensa para ropa caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda264-prensa-para-ropa-caja-plastica-560?min_price=20.0` },
    { id: 501, qty: 10, name: 'Rasuradora 20 Unid paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda205-rasuradora-20-unid-paquete-501?min_price=20.0` },
    { id: 4917, qty: BANCO_CONFIG.QTY, name: 'Recortes Varios 4Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda507-recortes-varios-4kg-caja-plastica-6203?min_price=20.0` },
    { id: 2503, qty: BANCO_CONFIG.QTY, name: 'Sal 10 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda187-sal-10-kg-caja-plastica-3789?min_price=20.0` },
    { id: 426, qty: BANCO_CONFIG.QTY, name: 'Salsa de tomate 10 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda032-salsa-de-tomate-10-kg-caja-plastica-426?min_price=20.0` },
    { id: 488, qty: BANCO_CONFIG.QTY, name: 'Sardinas 15 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda094-sardinas-15-kg-caja-plastica-488?min_price=20.0` },
    { id: 532, qty: BANCO_CONFIG.QTY, name: 'Shampoo varios 15 Lts caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda236-shampoo-varios-15-lts-caja-plastica-532?min_price=20.0` },
    { id: 490, qty: BANCO_CONFIG.QTY, name: 'Sirope 15 Lts caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda096-sirope-15-lts-caja-plastica-490?min_price=20.0` },
    { id: 403, qty: BANCO_CONFIG.QTY, name: 'Snacks varios 4 Kg caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda009-snacks-varios-4-kg-caja-plastica-403?min_price=20.0` },
    { id: 430, qty: BANCO_CONFIG.QTY, name: 'Sopa instantánea 3 Kg plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda036-sopa-instantanea-3-kg-plastica-430?min_price=20.0` },
    { id: 520, qty: BANCO_CONFIG.QTY, name: 'Suavizante para ropa 10 Lts caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda224-suavizante-para-ropa-10-lts-caja-plastica-520?min_price=20.0` },
    { id: 454, qty: BANCO_CONFIG.QTY, name: 'Sustituto de azúcar 1 Kg  paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda060-sustituto-de-azucar-1-kg-paquete-454?page=2&min_price=20.0` },
    { id: 417, qty: BANCO_CONFIG.QTY, name: 'Té varios 1 kg paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda023-te-varios-1-kg-paquete-417?page=2&min_price=20.0` },
    { id: 565, qty: BANCO_CONFIG.QTY, name: 'Tintes para el cabello caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda269-tintes-para-el-cabello-caja-plastica-565?min_price=20.0` },
    { id: 524, qty: BANCO_CONFIG.QTY, name: 'Toallas femeninas C/S Alas 300 paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda228-toallas-femeninas-c-s-alas-300-paquete-524?min_price=20.0` },
    { id: 505, qty: BANCO_CONFIG.QTY, name: 'Toallas de cocina y servilletas 12 Rollos paquete', referrer: `${BANCO_CONFIG.SHOP_URL}/bda209-toallas-de-cocina-y-servilletas-12-rollos-paquete-505?min_price=20.0` },
    { id: 526, qty: BANCO_CONFIG.QTY, name: 'Toallitas secas caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda230-toallitas-secas-caja-plastica-526?min_price=20.0` },
    { id: 1015, qty: BANCO_CONFIG.QTY, name: 'Vinagre varios 15 kg por caja plástica', referrer: `${BANCO_CONFIG.SHOP_URL}/bda105-vinagre-varios-15-kg-por-caja-plastica-2291?min_price=20.0` },
];
